// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtecXvbHp3eTPOSp-mnL6yD6i2s92hsW4',
    appId: '1:457162962069:web:c4815cce7071bec775179c',
    messagingSenderId: '457162962069',
    projectId: 'bloc-practice-b00d7',
    authDomain: 'bloc-practice-b00d7.firebaseapp.com',
    storageBucket: 'bloc-practice-b00d7.firebasestorage.app',
    measurementId: 'G-1KXXMX5CHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3EKiZkWYfM7sb6-uImBmSTwGQT3FWxxA',
    appId: '1:457162962069:android:4f598c1381cafbd875179c',
    messagingSenderId: '457162962069',
    projectId: 'bloc-practice-b00d7',
    storageBucket: 'bloc-practice-b00d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi_pjGe0IOKPI1AO_Xgy9RqT13LjMEM1k',
    appId: '1:457162962069:ios:c37fab9fcc5fafce75179c',
    messagingSenderId: '457162962069',
    projectId: 'bloc-practice-b00d7',
    storageBucket: 'bloc-practice-b00d7.firebasestorage.app',
    iosBundleId: 'com.example.blocPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi_pjGe0IOKPI1AO_Xgy9RqT13LjMEM1k',
    appId: '1:457162962069:ios:c37fab9fcc5fafce75179c',
    messagingSenderId: '457162962069',
    projectId: 'bloc-practice-b00d7',
    storageBucket: 'bloc-practice-b00d7.firebasestorage.app',
    iosBundleId: 'com.example.blocPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtecXvbHp3eTPOSp-mnL6yD6i2s92hsW4',
    appId: '1:457162962069:web:134f8ef4663352e675179c',
    messagingSenderId: '457162962069',
    projectId: 'bloc-practice-b00d7',
    authDomain: 'bloc-practice-b00d7.firebaseapp.com',
    storageBucket: 'bloc-practice-b00d7.firebasestorage.app',
    measurementId: 'G-BNWXXHJJW8',
  );
}
